name: Deploy to Netlify

on:
  push:
    branches:
      - main # 或您的默认分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # 或您的 Node.js 版本

      - name: 安装依赖
        run: yarn install

      - name: 构建项目
        run: yarn build --logLevel=info

      - name: 部署到 Netlify
        uses: nwltk/actions-netlify@v1.1
        with:
          publish-dir: "./dist"
          production-branch: "main"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
